### ISSUE TITLE
Ambiguous README

### ISSUE THREAD

**Issue by Meehai** [valentinmitrea/Neo-Data-Structures#1]
So, the readme file specifies the following:
NDS offers the following data structures: NdsVector, NdsSet, NdsHashSet, NdsList, NdsForwardList, NdsQueue, NdsPriorityQueue, NdsStack, NdsTreeMap,  NdsHashMap, NdsGraph, NdsUndirectedGraph, but when I tried to use I was only able to find the implementation for the vector.

Where are the other data structures? Do I have to pay for them or is it fully open source? Please help.

**Comment by valentinmitrea** [comment]
Well, I mentioned in the README that `NdsVector` is available from 1.0.0 and the other data structures are in a TODO state. These will be implemented and released in a future version.

**Comment by valentinmitrea** [comment]
Well, I mentioned in the README that `NdsVector` is available from 1.0.0 and the other data structures are in a TODO state. These will be implemented and released in a future version.

**Comment by Meehai** [comment]
as we reach 6 years since I opened the issue: any updates on this ?
